_wandb:
    value:
        cli_version: 0.22.1
        e:
            hhdby1oaid24jqya6r57acvslzmle29e:
                codePath: evaluate.py
                codePathLocal: evaluate.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "46194978816"
                email: tanyasrivastava656@gmail.com
                executable: /opt/venv/bin/python
                git:
                    commit: 4f9d5509d1961f9a75e007ab8f742726923d9864
                    remote: https://github.com/Tanyasrivastava4/fine_tuning_lab-project.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-410d6a59-03ed-d945-f07b-a3dc7cb5d799
                host: 6bd5df7e-09d9-43d3-a21a-a633f2f62766
                memory:
                    total: "25327493120"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /fine_tuning_lab-project/evaluate.py
                python: CPython 3.12.3
                root: /fine_tuning_lab-project
                startedAt: "2025-09-30T11:24:23.340359Z"
                writerId: hhdby1oaid24jqya6r57acvslzmle29e
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 2
                - 13
            "4": 3.12.3
            "5": 0.22.1
            "6": 4.56.2
            "12": 0.22.1
            "13": linux-x86_64
