_name_or_path:
    value: microsoft/phi-3-mini-4k-instruct
_wandb:
    value:
        cli_version: 0.22.1
        e:
            ngurdza26qmpjfyd08e1wrdpzm4r6bvu:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "31085486080"
                email: tanyasrivastava656@gmail.com
                executable: /opt/venv/bin/python
                git:
                    commit: 4f9d5509d1961f9a75e007ab8f742726923d9864
                    remote: https://github.com/Tanyasrivastava4/fine_tuning_lab-project.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-410d6a59-03ed-d945-f07b-a3dc7cb5d799
                host: 6bd5df7e-09d9-43d3-a21a-a633f2f62766
                memory:
                    total: "25327493120"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /fine_tuning_lab-project/train.py
                python: CPython 3.12.3
                root: /fine_tuning_lab-project
                startedAt: "2025-09-30T11:16:56.598691Z"
                writerId: ngurdza26qmpjfyd08e1wrdpzm4r6bvu
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 7
                - 19
                - 62
                - 66
            "4": 3.12.3
            "5": 0.22.1
            "6": 4.56.2
            "9":
                "1": transformers_trainer
            "12": 0.22.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Phi3ForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
auto_map:
    value:
        AutoConfig: configuration_phi3.Phi3Config
        AutoModelForCausalLM: modeling_phi3.Phi3ForCausalLM
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: float32
early_stopping:
    value: false
embd_pdrop:
    value: 0
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 32000
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 3072
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": 0
        "1": 1
        "2": 2
        "3": 3
        "4": 5
        "5": 8
        "6": 9
        "7": 10
        "8": 11
        "9": 13
        "10": 14
        "11": 15
        "12": 18
        "13": 20
        "14": 21
        "15": 23
        "16": 24
        "17": 25
        "18": 26
        "19": 27
        "20": 28
        "21": 32
        "22": 34
        "23": 36
        "24": 37
        "25": 38
        "26": 40
        "27": 43
        "28": 44
        "29": 45
        "30": 46
        "31": 47
        "32": 48
        "33": 50
        "34": 51
        "35": 52
        "36": 53
        "37": 55
        "38": 56
        "39": 57
        "40": 58
        "41": 59
        "42": 60
        "43": 61
        "44": 62
        "45": 63
        "46": 64
        "47": 65
        "48": 67
        "49": 72
        "50": 74
        "51": 75
        "52": 77
        "53": 79
        "54": 81
        "55": 82
        "56": 85
        "57": 86
        "58": 89
        "59": 90
        "60": 91
        "61": 92
        "62": 94
        "63": 97
        "64": 98
        "65": 99
        "66": 100
        "67": 101
        "68": 102
        "69": 103
        "70": 104
        "71": 105
        "72": 106
        "73": 107
        "74": 108
        "75": 110
        "76": 111
        "77": 113
        "78": 115
        "79": 117
        "80": 118
        "81": 120
        "82": 123
        "83": 124
        "84": 126
        "85": 129
        "86": 130
        "87": 132
        "88": 133
        "89": 134
        "90": 135
        "91": 136
        "92": 139
        "93": 140
        "94": 141
        "95": 142
        "96": 146
        "97": 147
        "98": 149
        "99": 150
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 8192
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        "0": 0
        "1": 1
        "2": 2
        "3": 3
        "5": 4
        "8": 5
        "9": 6
        "10": 7
        "11": 8
        "13": 9
        "14": 10
        "15": 11
        "18": 12
        "20": 13
        "21": 14
        "23": 15
        "24": 16
        "25": 17
        "26": 18
        "27": 19
        "28": 20
        "32": 21
        "34": 22
        "36": 23
        "37": 24
        "38": 25
        "40": 26
        "43": 27
        "44": 28
        "45": 29
        "46": 30
        "47": 31
        "48": 32
        "50": 33
        "51": 34
        "52": 35
        "53": 36
        "55": 37
        "56": 38
        "57": 39
        "58": 40
        "59": 41
        "60": 42
        "61": 43
        "62": 44
        "63": 45
        "64": 46
        "65": 47
        "67": 48
        "72": 49
        "74": 50
        "75": 51
        "77": 52
        "79": 53
        "81": 54
        "82": 55
        "85": 56
        "86": 57
        "89": 58
        "90": 59
        "91": 60
        "92": 61
        "94": 62
        "97": 63
        "98": 64
        "99": 65
        "100": 66
        "101": 67
        "102": 68
        "103": 69
        "104": 70
        "105": 71
        "106": 72
        "107": 73
        "108": 74
        "110": 75
        "111": 76
        "113": 77
        "115": 78
        "117": 79
        "118": 80
        "120": 81
        "123": 82
        "124": 83
        "126": 84
        "129": 85
        "130": 86
        "132": 87
        "133": 88
        "134": 89
        "135": 90
        "136": 91
        "139": 92
        "140": 93
        "141": 94
        "142": 95
        "146": 96
        "147": 97
        "149": 98
        "150": 99
learning_rate:
    value: 0.0002
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./fine_tuned_model/runs/Sep30_11-14-42_6bd5df7e-09d9-43d3-a21a-a633f2f62766
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 4096
max_steps:
    value: -1
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 3735776256
model_type:
    value: phi3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_key_value_heads:
    value: 32
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
original_max_position_embeddings:
    value: 4096
output_attentions:
    value: false
output_dir:
    value: ./fine_tuned_model
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 32000
parallelism_config:
    value: null
partial_rotary_factor:
    value: 1
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: microsoft/phi-3-mini-4k-instruct
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save:
                - classifier
                - score
            peft_type: LORA
            qalora_group_size: 16
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - qkv_proj
                - gate_up_proj
                - down_proj
                - o_proj
            target_parameters: null
            task_type: SEQ_CLS
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
resid_pdrop:
    value: 0
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-05
rope_scaling:
    value: null
rope_theta:
    value: 10000
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: 2047
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.56.2
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32064
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
